### ISSUE TITLE
Request: expose CardCornerRadius + Elevation

### ISSUE THREAD

**Issue by moelle89** [OpenSooq/Gligar#1]
Would it be possible to be able to change the cardcornerradius aswell as the card elevation?

**Comment by hani-momanii** [comment]
For now, no.
Will be added to the next version.

**Comment by hani-momanii** [comment]
[Added on v1.1.0.](https://github.com/OpenSooq/Gligar/releases/tag/v1.1.0)
You can override any of [these values](https://github.com/OpenSooq/Gligar/blob/4d2d5e40b9a652e9fc868fec8c87b4786d069be6/gligar/src/main/res/values/dimens.xml)
