### ISSUE TITLE
Picker fails to load images from storage on Android 10.

### ISSUE THREAD

**Issue by OdeyFox** [OpenSooq/Gligar#4]
The picker works fine on versions prior to android 10. Taking photos works fine but the picker fails to load local images into the grid.

**Comment by hani-momanii** [comment]
Can you add more details on the issues, folders or the path of the images?

**Comment by OdeyFox** [comment]
When i launch the picker it retrieves all the folder names correctly, and no matter the folder i choose, it returns this:

![Screenshot_20200225-180935](https://user-images.githubusercontent.com/29254668/76155087-e42fa780-60ef-11ea-8d76-d1f0b69805c5.jpg)


i have tested the picker on android 9 and below and it works just fine.

**Comment by JarnoVgr** [comment]
Probably requires `android:requestLegacyExternalStorage="true"` in the `<application>` part of your manifest.

Please note this workaround will most likely only work for Android 10 and not the upcoming Android 11.

**Comment by hani-momanii** [comment]
Fixed on v1.1.0.
