### ISSUE TITLE
how do i implement this for single photo pick in java. with fragment?

### ISSUE THREAD

**Issue by rohitchavan7** [OpenSooq/Gligar#5]

**Comment by hani-momanii** [comment]
you can set the limit to 1.

**Comment by muhammadkamranlatifraza** [comment]
this has two problems, first it wont let any other image selected as it requires second user will have to deselect and then only it can select new image and proceeded with it, 

either this 
new Gligar().requestCode(PICKER_REQUEST_CODE).withFragment(this).limit(1).show()
should allow selection of other images while one is selected or setSingleSelection(true) should be made that could introduce such behavior

_Praises to creator_
