### ISSUE TITLE
We can also add in which way you open a picker in landscape or portrait.

### ISSUE THREAD

**Issue by harishantino** [OpenSooq/Gligar#6]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by harishantino** [comment]
I want to open this library in landscape mode. but it always opens in a  portrait mode is there any way to handle this or this one is a bug.

**Comment by fluke24sk** [comment]
You can add manifest activity in your project for other mode

```
<activity
            android:name="com.opensooq.supernova.gligar.ui.ImagePickerActivity"
            tools:replace="android:screenOrientation"
            android:screenOrientation="landscape"
            android:theme="@style/LibTheme" /> 
```
