### ISSUE TITLE
Camera captured image not shown in gallery.

### ISSUE THREAD

**Issue by raviyadav5951** [OpenSooq/Gligar#7]
If we select the camera to click picture then it shows the image in grid for then . But when we open the gallery app then that captured images are not shown in gallery.

-Device :Asus Max Pro M1
 - OS: Android Pie

**Comment by hani-momanii** [comment]
@raviyadav5951  Taken image can be found inside the Pictures directory.

**Comment by raviyadav5951** [comment]
Ok.

**Comment by Asad-Shafique** [comment]
Taken images are not found in Pictures directory. Can anyone tell me how to save image in gallery from this library ?
